#include "User.h"
#include "Str.h"
#ifndef LIBRARY_SYSTEM_PROJECT_FUNCTIONALITIES_H
#define LIBRARY_SYSTEM_PROJECT_FUNCTIONALITIES_H
void printHeader();
void printMemberMenu();
void printSearchOptions();
void printLibMenu();
bool checkBack();
bool checkClose();
void printExit();
void searchByISBN();
void searchByYear();
void searchByTitle();
void searchByAuthor();
void searchByGenre();
void searchForBook();
void viewAvailableBooks();
void addToCart();
void viewCart();
void updateMemberData();
void updateBookData();
void updateMemberMenu();
void updateBookMenu();
void updatepassword();
void diplaydata();
void loanrequest(str);
void viewloans();
void processloans();
void checkforoverdues();
void returnbook();
User* login();
void memberMenu();
void libMenu();
#endif //LIBRARY_SYSTEM_PROJECT_FUNCTIONALITIES_H
